# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Sem6/CS765/Ass1/Blockchain-Simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Sem6/CS765/Ass1/Blockchain-Simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Sem6/CS765/Ass1/Blockchain-Simulator/CMakeFiles /mnt/d/Sem6/CS765/Ass1/Blockchain-Simulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Sem6/CS765/Ass1/Blockchain-Simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simulator

# Build rule for target.
simulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulator
.PHONY : simulator

# fast build rule for target.
simulator/fast:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/build
.PHONY : simulator/fast

src/block.o: src/block.cpp.o

.PHONY : src/block.o

# target to build an object file
src/block.cpp.o:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/block.cpp.o
.PHONY : src/block.cpp.o

src/block.i: src/block.cpp.i

.PHONY : src/block.i

# target to preprocess a source file
src/block.cpp.i:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/block.cpp.i
.PHONY : src/block.cpp.i

src/block.s: src/block.cpp.s

.PHONY : src/block.s

# target to generate assembly for a file
src/block.cpp.s:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/block.cpp.s
.PHONY : src/block.cpp.s

src/event_queue.o: src/event_queue.cpp.o

.PHONY : src/event_queue.o

# target to build an object file
src/event_queue.cpp.o:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/event_queue.cpp.o
.PHONY : src/event_queue.cpp.o

src/event_queue.i: src/event_queue.cpp.i

.PHONY : src/event_queue.i

# target to preprocess a source file
src/event_queue.cpp.i:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/event_queue.cpp.i
.PHONY : src/event_queue.cpp.i

src/event_queue.s: src/event_queue.cpp.s

.PHONY : src/event_queue.s

# target to generate assembly for a file
src/event_queue.cpp.s:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/event_queue.cpp.s
.PHONY : src/event_queue.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/peer.o: src/peer.cpp.o

.PHONY : src/peer.o

# target to build an object file
src/peer.cpp.o:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/peer.cpp.o
.PHONY : src/peer.cpp.o

src/peer.i: src/peer.cpp.i

.PHONY : src/peer.i

# target to preprocess a source file
src/peer.cpp.i:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/peer.cpp.i
.PHONY : src/peer.cpp.i

src/peer.s: src/peer.cpp.s

.PHONY : src/peer.s

# target to generate assembly for a file
src/peer.cpp.s:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/peer.cpp.s
.PHONY : src/peer.cpp.s

src/simulator.o: src/simulator.cpp.o

.PHONY : src/simulator.o

# target to build an object file
src/simulator.cpp.o:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/simulator.cpp.o
.PHONY : src/simulator.cpp.o

src/simulator.i: src/simulator.cpp.i

.PHONY : src/simulator.i

# target to preprocess a source file
src/simulator.cpp.i:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/simulator.cpp.i
.PHONY : src/simulator.cpp.i

src/simulator.s: src/simulator.cpp.s

.PHONY : src/simulator.s

# target to generate assembly for a file
src/simulator.cpp.s:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/simulator.cpp.s
.PHONY : src/simulator.cpp.s

src/transaction.o: src/transaction.cpp.o

.PHONY : src/transaction.o

# target to build an object file
src/transaction.cpp.o:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/transaction.cpp.o
.PHONY : src/transaction.cpp.o

src/transaction.i: src/transaction.cpp.i

.PHONY : src/transaction.i

# target to preprocess a source file
src/transaction.cpp.i:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/transaction.cpp.i
.PHONY : src/transaction.cpp.i

src/transaction.s: src/transaction.cpp.s

.PHONY : src/transaction.s

# target to generate assembly for a file
src/transaction.cpp.s:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/transaction.cpp.s
.PHONY : src/transaction.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... simulator"
	@echo "... src/block.o"
	@echo "... src/block.i"
	@echo "... src/block.s"
	@echo "... src/event_queue.o"
	@echo "... src/event_queue.i"
	@echo "... src/event_queue.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/peer.o"
	@echo "... src/peer.i"
	@echo "... src/peer.s"
	@echo "... src/simulator.o"
	@echo "... src/simulator.i"
	@echo "... src/simulator.s"
	@echo "... src/transaction.o"
	@echo "... src/transaction.i"
	@echo "... src/transaction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

